# Справочник полей для application.yaml + application-{profile}.yaml

contour: sandbox

logging:
  app: DEBUG
  uvicorn: INFO
  uvicorn_access: INFO
  uvicorn_error: INFO

kafka:
  enabled: true
  bootstrap_servers: gitlab-ci.ru:9092
  input_topic: frap-llm-helper-in
  output_topic: frap-llm-helper-out
  group_id: frap-llm-helper-reader
  output_dir: received_messages
  files_root: .
  send_json:
  send_json_file:

# Вариант 1: отдельные поля
database:
  url: jdbc:postgresql://89.108.103.170:5432
  username: fsrar_user
  password: Qwerty1234

# Вариант 2: одной строкой dsn
# database:
#   dsn: postgresql://fsrar_user:Qwerty1234@89.108.103.170:5432

# Вариант 3: dsn без логина/пароля + поля отдельно
# database:
#   dsn: postgresql://89.108.103.170:5432
#   username: fsrar_user
#   password: Qwerty1234

# Environment (yaml → K8S, UPPERCASE, точки на _):
# PYTHON_PROFILES_ACTIVE=sandbox
# DATABASE_URL=jdbc:postgresql://host:5432
